// 网站数据
const initialData = {
  categories: [
    {
      id: "common-tools",
      name: "commonTools",
      icon: "fas fa-tools",
      sites: [
        {
          id: "google",
          name: "Google",
          url: "https://www.google.com",
          description: "The world's most popular search engine",
          logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
        },
        {
          id: "bing",
          name: "Bing",
          url: "https://www.bing.com",
          description: "Microsoft's search engine with AI features",
          logo: "https://www.bing.com/sa/simg/favicon-2x.ico",
        },
        {
          id: "baidu",
          name: "百度",
          url: "https://www.baidu.com",
          description: "中国最大的搜索引擎",
          logo: "https://www.baidu.com/img/flexible/logo/pc/result.png",
        },
        {
          id: "google-docs",
          name: "Google Docs",
          url: "https://docs.google.com",
          description: "Free online document editor from Google",
          logo: "https://ssl.gstatic.com/docs/documents/images/kix-favicon7.ico",
        },
        {
          id: "office365",
          name: "Office 365",
          url: "https://www.office.com",
          description: "Microsoft's online office suite",
          logo: "https://www.microsoft.com/favicon.ico",
        },
        {
          id: "tencent-docs",
          name: "腾讯文档",
          url: "https://docs.qq.com",
          description: "腾讯推出的在线协作文档",
          logo: "https://docs.qq.com/favicon.ico",
        },
        {
          id: "dropbox",
          name: "Dropbox",
          url: "https://www.dropbox.com",
          description: "Cloud storage and file sharing service",
          logo: "https://www.dropbox.com/static/30168/images/favicon.ico",
        },
        {
          id: "onedrive",
          name: "OneDrive",
          url: "https://onedrive.live.com",
          description: "Microsoft's cloud storage service",
          logo: "https://onedrive.live.com/favicon.ico",
        },
        {
          id: "baidu-pan",
          name: "百度网盘",
          url: "https://pan.baidu.com",
          description: "百度旗下的个人云存储服务",
          logo: "https://pan.baidu.com/box-static/disk-system/images/favicon.ico",
        },
        {
          id: "canva",
          name: "Canva",
          url: "https://www.canva.com",
          description: "Online design and publishing tool",
          logo: "https://static.canva.com/static/images/favicon.ico",
        },
        {
          id: "figma",
          name: "Figma",
          url: "https://www.figma.com",
          description: "Collaborative interface design tool",
          logo: "https://static.figma.com/app/icon/1/favicon.svg",
        },
        {
          id: "huaban",
          name: "花瓣网",
          url: "https://huaban.com",
          description: "中国领先的图片素材及创意社区",
          logo: "https://huaban.com/favicon.ico",
        },
        {
          id: "notion",
          name: "Notion",
          url: "https://www.notion.so",
          description: "All-in-one workspace for notes and tasks",
          logo: "https://www.notion.so/images/favicon.ico",
        },
        {
          id: "trello",
          name: "Trello",
          url: "https://trello.com",
          description: "Visual tool for organizing your work",
          logo: "https://trello.com/favicon.ico",
        },
        {
          id: "dida",
          name: "滴答清单",
          url: "https://www.dida365.com",
          description: "专注日历提醒与时间管理的应用",
          logo: "https://www.dida365.com/favicon.ico",
        },
      ],
    },
    {
      id: "ai-tools",
      name: "aiTools",
      icon: "fas fa-robot",
      sites: [
        {
          id: "chatgpt",
          name: "ChatGPT",
          url: "https://chat.openai.com",
          description: "OpenAI's conversational AI assistant",
          logo: "https://chat.openai.com/favicon.ico",
        },
        {
          id: "claude",
          name: "Claude",
          url: "https://claude.ai",
          description: "Anthropic's AI assistant",
          logo: "https://claude.ai/favicon.ico",
        },
        {
          id: "wenxin",
          name: "文心一言",
          url: "https://yiyan.baidu.com",
          description: "百度推出的知识增强大语言模型",
          logo: "https://yiyan.baidu.com/favicon.ico",
        },
        {
          id: "huggingface",
          name: "HuggingFace",
          url: "https://huggingface.co",
          description: "The AI community building the future",
          logo: "https://huggingface.co/favicon.ico",
        },
        {
          id: "replicate",
          name: "Replicate",
          url: "https://replicate.com",
          description: "Run machine learning models in the cloud",
          logo: "https://replicate.com/favicon.ico",
        },
        {
          id: "midjourney",
          name: "MidJourney",
          url: "https://www.midjourney.com",
          description: "AI image generation via Discord",
          logo: "https://www.midjourney.com/favicon.ico",
        },
        {
          id: "stable-diffusion",
          name: "Stable Diffusion",
          url: "https://stability.ai",
          description: "Open source text-to-image AI model",
          logo: "https://stability.ai/favicon.ico",
        },
        {
          id: "leonardo",
          name: "Leonardo.ai",
          url: "https://leonardo.ai",
          description: "Create stunning game assets with AI",
          logo: "https://leonardo.ai/favicon.ico",
        },
        {
          id: "jasper",
          name: "Jasper",
          url: "https://www.jasper.ai",
          description: "AI content platform for marketing teams",
          logo: "https://www.jasper.ai/favicon.ico",
        },
        {
          id: "copyai",
          name: "Copy.ai",
          url: "https://www.copy.ai",
          description: "AI-powered copywriter for businesses",
          logo: "https://www.copy.ai/favicon.ico",
        },
        {
          id: "mita",
          name: "秘塔写作猫",
          url: "https://xiezuocat.com",
          description: "中文写作辅助和校对工具",
          logo: "https://xiezuocat.com/favicon.ico",
        },
        {
          id: "runway",
          name: "Runway",
          url: "https://runwayml.com",
          description: "AI magic tools for creators",
          logo: "https://runwayml.com/favicon.ico",
        },
        {
          id: "pictory",
          name: "Pictory",
          url: "https://pictory.ai",
          description: "Create videos from text automatically",
          logo: "https://pictory.ai/favicon.ico",
        },
        {
          id: "jianying",
          name: "剪映AI",
          url: "https://www.capcut.cn",
          description: "字节跳动旗下的智能视频剪辑工具",
          logo: "https://www.capcut.cn/favicon.ico",
        },
      ],
    },
    {
      id: "dev-tools",
      name: "devTools",
      icon: "fas fa-code",
      sites: [
        {
          id: "github",
          name: "GitHub",
          url: "https://github.com",
          description: "Where the world builds software",
          logo: "https://github.com/favicon.ico",
        },
        {
          id: "gitlab",
          name: "GitLab",
          url: "https://gitlab.com",
          description: "DevOps platform for software development",
          logo: "https://gitlab.com/favicon.ico",
        },
        {
          id: "gitee",
          name: "Gitee",
          url: "https://gitee.com",
          description: "中国领先的代码托管平台",
          logo: "https://gitee.com/favicon.ico",
        },
        {
          id: "codesandbox",
          name: "CodeSandbox",
          url: "https://codesandbox.io",
          description: "Online code editor for web development",
          logo: "https://codesandbox.io/favicon.ico",
        },
        {
          id: "stackblitz",
          name: "StackBlitz",
          url: "https://stackblitz.com",
          description: "Online IDE for web applications",
          logo: "https://stackblitz.com/favicon.ico",
        },
        {
          id: "postman",
          name: "Postman",
          url: "https://www.postman.com",
          description: "API platform for building and using APIs",
          logo: "https://www.postman.com/favicon.ico",
        },
        {
          id: "apifox",
          name: "Apifox",
          url: "https://www.apifox.cn",
          description: "API 文档、调试、Mock、测试一体化协作平台",
          logo: "https://www.apifox.cn/favicon.ico",
        },
        {
          id: "leetcode",
          name: "LeetCode",
          url: "https://leetcode.com",
          description: "The best platform to help you enhance your skills",
          logo: "https://leetcode.com/favicon.ico",
        },
        {
          id: "nowcoder",
          name: "牛客网",
          url: "https://www.nowcoder.com",
          description: "中国领先的IT人才成长平台",
          logo: "https://www.nowcoder.com/favicon.ico",
        },
        {
          id: "mdn",
          name: "MDN Web Docs",
          url: "https://developer.mozilla.org",
          description: "Resources for developers, by developers",
          logo: "https://developer.mozilla.org/favicon.ico",
        },
        {
          id: "runoob",
          name: "菜鸟教程",
          url: "https://www.runoob.com",
          description: "提供了编程的基础技术教程",
          logo: "https://www.runoob.com/favicon.ico",
        },
      ],
    },
    {
      id: "practical-tools",
      name: "practicalTools",
      icon: "fas fa-wrench",
      sites: [
        {
          id: "smallpdf",
          name: "Smallpdf",
          url: "https://smallpdf.com",
          description: "Easy-to-use PDF converter and editor",
          logo: "https://smallpdf.com/favicon.ico",
        },
        {
          id: "convertio",
          name: "Convertio",
          url: "https://convertio.co",
          description: "File converter for various formats",
          logo: "https://convertio.co/favicon.ico",
        },
        {
          id: "tinypng",
          name: "TinyPNG",
          url: "https://tinypng.com",
          description: "Smart PNG and JPEG compression",
          logo: "https://tinypng.com/favicon.ico",
        },
        {
          id: "removebg",
          name: "Remove.bg",
          url: "https://www.remove.bg",
          description: "Remove image backgrounds automatically",
          logo: "https://www.remove.bg/favicon.ico",
        },
        {
          id: "tempmail",
          name: "TempMail",
          url: "https://temp-mail.org",
          description: "Disposable temporary email service",
          logo: "https://temp-mail.org/favicon.ico",
        },
        {
          id: "10minutemail",
          name: "10分钟邮箱",
          url: "https://10minutemail.com",
          description: "Temporary email for safer online experience",
          logo: "https://10minutemail.com/favicon.ico",
        },
        {
          id: "jsonformatter",
          name: "JSON Formatter",
          url: "https://jsonformatter.curiousconcept.com",
          description: "Validate and format JSON data",
          logo: "https://jsonformatter.curiousconcept.com/favicon.ico",
        },
        {
          id: "prettier",
          name: "Prettier",
          url: "https://prettier.io/playground",
          description: "Opinionated code formatter",
          logo: "https://prettier.io/favicon.ico",
        },
        {
          id: "speedtest",
          name: "Speedtest",
          url: "https://www.speedtest.net",
          description: "Test your internet speed",
          logo: "https://www.speedtest.net/favicon.ico",
        },
        {
          id: "pingpe",
          name: "Ping.pe",
          url: "https://ping.pe",
          description: "Multi-server ping and traceroute tool",
          logo: "https://ping.pe/favicon.ico",
        },
      ],
    },
  ],
}

// 多语言支持
const translations = {
  zh: {
    siteName: "WebNav 导航",
    searchPlaceholder: "输入关键词搜索...",
    darkMode: "暗黑模式",
    lightMode: "明亮模式",
    switchLanguage: "切换语言",
    totalVisits: "总访问量",
    todayVisits: "今日访问",
    totalSites: "网站总数",
    commonTools: "常用工具",
    aiTools: "AI专区",
    devTools: "开发者工具",
    practicalTools: "实用工具",
    addSite: "添加网站",
    removeSite: "删除网站",
    addNewSite: "添加新网站",
    siteName: "网站名称",
    siteUrl: "网站地址",
    siteDescription: "网站描述",
    siteLogo: "网站图标",
    enterSiteName: "输入网站名称",
    enterSiteUrl: "输入网站地址",
    enterSiteDescription: "输入网站描述",
    enterSiteLogoUrl: "输入网站图标地址",
    add: "添加",
    cancel: "取消",
    history: "历史记录",
    recentHistory: "最近访问",
    noHistory: "暂无历史记录",
    clearHistory: "清空历史",
    exportConfig: "导出配置",
    importConfig: "导入配置",
    allRightsReserved: "版权所有",
  },
  en: {
    siteName: "WebNav Hub",
    searchPlaceholder: "Search anything...",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    switchLanguage: "Switch Language",
    totalVisits: "Total Visits",
    todayVisits: "Today Visits",
    totalSites: "Total Sites",
    commonTools: "Common Tools",
    aiTools: "AI Tools",
    devTools: "Developer Tools",
    practicalTools: "Practical Tools",
    addSite: "Add Site",
    removeSite: "Remove Site",
    addNewSite: "Add New Site",
    siteName: "Site Name",
    siteUrl: "Site URL",
    siteDescription: "Site Description",
    siteLogo: "Site Logo",
    enterSiteName: "Enter site name",
    enterSiteUrl: "Enter site URL",
    enterSiteDescription: "Enter site description",
    enterSiteLogoUrl: "Enter site logo URL",
    add: "Add",
    cancel: "Cancel",
    history: "History",
    recentHistory: "Recent History",
    noHistory: "No history yet",
    clearHistory: "Clear History",
    exportConfig: "Export Config",
    importConfig: "Import Config",
    allRightsReserved: "All Rights Reserved",
  },
}

